### ISSUE TITLE
Allow running a skill that isn't yet local

### ISSUE THREAD

**Issue by haacked** [aseriousbiz/abbot-cli#10]
Right now, `abbot run` will only run a skill that is in your Abbot Workspace (aka you ran `abbot get {skill}` previously). However, it may be useful to be able to run a skill from your local machine that hasn't been downloaded.

1. Say you're editing a skill and you have local changes, but you want to compare what happens with the current version on the server. You may want to do something like `abbot run {skill} --deployed` to run the deployed version of the skill.
2. You might be setting up automation you want to kick off from your local machine. While we think the whole point of Abbot is to initiate automation from Chat where it's more visible and where others can learn from it, there may still be valid reasons to kick off automation from your local machine. And if you use `abbot-cli` to do so, you still get all the other Abbot benefits such as auditing, secret management, etc.

**Comment by shana** [comment]
hmmmm yeah that would be really interesting! Even for just managing skill versions it would be useful - having a way of listing skills and seeing which ones came from packages, what versions they are, whether they have changes, and being able to run the deployed version, this would all be very useful.
